version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: '!ChangeMe!'
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
