# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://app:Pass@123!@database/app
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: Pass@123!
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
